collections:
  articles:
  article_sections:
    output: true

defaults:
  - scope:
      path: ""
      type: "article_sections"
    values:
      layout: "article_section"

text_colors:
  green:   "#b2ff59"  # Light Gren A200
  blue:    "#40c4ff"  # Light Blue A200
  red:     "#ffab40"  # Orange A200
  darkred: "#ff6e40"  # Deep Orange A200
